name: Python App Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Specify your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Deploy to Streamlit
      - name: Deploy to Streamlit
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}  # Use GitHub Secrets to inject APP_TOKEN
        run: |
          echo "Deploying to Streamlit..."
          streamlit run main.py

